passable_area:
  ros__parameters:
    output:
      terrain_state_topic: "/terrain_state"
      terrain_cost_topic: "/terrain_cost"
      obstacle_points_topic: "/terrain_obstacle_points"
      debug_grid_map_topic: "/terrain_debug/grid_map"
      base_gravity_cloud_topic: "/terrain_debug/base_gravity_cloud"
      support_points_topic: "/terrain_debug/support_points"
      unknown_mask_topic: "/terrain_debug/unknown_mask"
      observability_topic: "/terrain_debug/observability"
    debug:
      publish_grid_map: true
      publish_points: true
      publish_base_gravity_cloud: true
      publish_observability: true
