passable_area:
  ros__parameters:
    map_length:    8.0
    map_width:     8.0
    map_height_min: -1.0
    map_height_max:  1.0
    voxel_size:    0.05
    max_drop:      0.25
    max_roughness: 0.10
    max_slope_deg: 89.0
    max_inpaint_pixels: 200
    enable_center_padding: true
    center_dist_thresh: 0.8
    enable_blind_check: false
    treat_nan_as_stiff: true

    accumulate_cloud_topic: "/accumulate_cloud/cloud_gravity"
    imu_topic: "/IMU"
    passable_cloud_topic: "/passable_area"
    impassable_cloud_topic: "/impassable_area"
    grid_map_topic: "/grid_map"
    traversal_cost_topic: "/traversal_cost"

    world_frame:   "camera_init"
    gravity_frame: "base_gravity"
    body_frame:    "base_link"
    used_frame:    "base_gravity"
    dog_model:     "m20"

    raycast:
      enable: true
      max_ray_distance: 4.0
      max_nan_gap: 3.0

    elevation_solver:
      use_histogram_solver: true
      histogram_bins: 20
      region_enabled: true
      region_min_x: -3.0
      region_max_x: 3.0
      region_min_y: -1.0
      region_max_y: 1.0

    traversal_cost:
      enable: false
      slope_free_deg: 10.0
      slope_block_deg: 80.0
      rough_free: 0.01
      rough_block: 0.04
      step_free: 0.08
      step_block: 0.35
      slope_weight: 0.3
      roughness_weight: 0.3
      step_weight: 0.4
      easy_cost: 0.0
      hard_cost: 90.0
      max_cost: 100.0
      missing_cost: 20.0
      curve_power: 1.0
      low_cost_filter_ratio: 0.1
      terrain_sample_window: 1
      safe_zone_side_length: 0.0
